### Create a new user

POST http://192.168.47.128:3003/auth/signup
content-type: application/json

{
    "email": "lola@example.com",
    "password": "Baxti"
}

### Find a user with a particular user ID
GET http://192.168.47.128:3003/auth/1

### Find all users with a given email
GET http://192.168.47.128:3003/auth?email=lola@example.com


### Delete a user with a given id
DELETE http://192.168.47.128:3003/auth/5